[package]
name = "voronoi"
version = "0.0.1"
authors = ["AndrÃ©-Patrick Bubel <code@andre-bubel.de>"]
build = "build.rs"

[dependencies]
libc = "*"

[dev-dependencies]
quickcheck = "0.2"
rand = "0.3"

[build-dependencies]
gcc = "0.3"
